'use client';
import Image from 'next/image';
import { useState } from 'react';
import { ContactLink } from './ContactLink';
import { trackEvent } from '@/lib/analytics';
import { money, type Product } from '@/lib/platform/types';
export function Catalog({ products = [], compact = false }: { products?: Product[]; compact?: boolean }) {
  const [category, setCategory] = useState('Todos');
  const [query, setQuery] = useState('');
  const categories = ['Todos', ...Array.from(new Set(products.map(p => p.category)))];
  const filtered = products.filter(p => (category === 'Todos' || p.category === category) && `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  return <section id="juguetes" className={`catalog-section section-wrap ${compact ? 'catalog-compact' : ''}`}><div className="catalog-heading"><div><div className="eyebrow">JUGUETES PARA SUS GRANDES IDEAS</div><h2>Su próxima <em>aventura.</em></h2><p className="muted">Descubre los productos participantes y compara tu precio de socio.</p></div><a className="text-link" href={compact ? '/catalogo' : '/#membresia'}>{compact ? 'Explorar el catálogo ↗' : 'Conocer la membresía ↗'}</a></div><div className="catalog-tools"><div className="filters" aria-label="Filtrar juguetes">{categories.map(item => <button key={item} aria-pressed={category === item} onClick={() => { setCategory(item); trackEvent('select_category', { category: item }); }}>{item === 'Todos' ? '✳ Todos' : item}</button>)}</div>{!compact && <label className="catalog-search"><span className="sr-only">Buscar juguetes</span><input type="search" placeholder="Buscar un juguete…" value={query} onChange={event => setQuery(event.target.value)} /></label>}</div><div className="toy-grid">{filtered.map((toy, i) => <article key={toy.id} className="toy-card"><div className={`toy-picture ${['peach','lavender','mint','butter'][i % 4]}`}><span className="toy-tag">{toy.stock === 0 ? 'Agotado' : toy.category}</span>{toy.image_url ? <Image src={toy.image_url} alt={toy.name} width={420} height={420} sizes="(max-width: 600px) 90vw, (max-width: 900px) 45vw, 23vw" /> : <div className="product-placeholder"><span aria-hidden="true">✦</span><strong>{toy.name}</strong><small>Fotografía próximamente</small></div>}</div><div className="toy-info"><small>{toy.age}</small><h3>{toy.name}</h3><p className="product-description">{toy.description}</p>{toy.price !== null ? <div className="product-prices"><span>Precio regular <b>{money(toy.price)}</b></span>{toy.member_price !== null && toy.member_price < toy.price && <><span className="member-price">Precio socio <strong>{money(toy.member_price)}</strong></span><small>Ahorras {money(toy.price - toy.member_price)} en este producto</small></>}</div> : <p className="price-pending">Consulta el precio y la disponibilidad</p>}{toy.stock !== 0 && <ContactLink location={`catalog_${toy.id}`} message={`Hola, me interesa ${toy.name}. ¿Me confirman el modelo, disponibilidad y precio${toy.member_price !== null ? ' de socio' : ''}?`} className="product-link">Consultar producto <span>↗</span></ContactLink>}</div></article>)}</div>{filtered.length === 0 && <div className="empty-state"><h3>{products.length ? 'No encontramos ese juguete.' : 'Estamos preparando el catálogo.'}</h3><p>{products.length ? 'Prueba otra palabra o categoría.' : 'Pronto podrás conocer los productos y precios participantes.'}</p></div>}<p className="catalog-note" aria-live="polite">{filtered.length} productos · Edad, existencias y condiciones se confirman por modelo. El precio de socio requiere membresía activa.</p></section>;
}

